### ISSUE TITLE
6d6f0ab did not increase version to 1.0.8

### ISSUE THREAD

**Issue by markfirmware** [vinodnimbalkar/svelte-pdf#10]
https://github.com/vinodnimbalkar/svelte-pdf/commit/6d6f0ab18098e5c52f62ef8f810d33220b56625b

**Comment by vinodnimbalkar** [comment]
Version updated - cc0ca5370647d662b16d80cb35bfe61e2e5c79bb

**Comment by markfirmware** [comment]
Thanks!
