### ISSUE TITLE
Control each option (print,download...) on its own rather than disable all options once or show them

### ISSUE THREAD

**Issue by Rachid09** [vinodnimbalkar/svelte-pdf#40]
It would be nice to have optional props to control each option on its own

For use cases where for example you  want to disable the download or print option for specific users of your application and still enable other options

and I would be glad to work on this enhancement feature if it's something you see that would be a great plus for this package

there are also some CSS control changes on the viewer that I would like to work on because I used this package in a project of mine lately, and it's a great package btw, and I needed to disable all options by controlling CSS and the classes globally in the application and I saw that the classes were very generic, so I might run over some CSS conflicts in the future.

**Comment by vinodnimbalkar** [comment]
@Rachid09 Please contribute to adding an enhancement feature.

**Comment by vinodnimbalkar** [comment]
fixed by #41
