### ISSUE TITLE
FileSaver default export

### ISSUE THREAD

**Issue by keops-sys** [vinodnimbalkar/svelte-pdf#46]
Hello,

I came accross this issue while using your amazing library:

`The requested module '/node_modules/file-saver/dist/FileSaver.min.js?v=9d52a9b1' does not provide an export named 'default' (at PdfViewer.svelte:5:10)`

![Screenshot 2022-12-11 at 18 59 12](https://user-images.githubusercontent.com/47661144/206920417-160e7617-9b24-4840-8942-ed84b1a66809.png)

which is:

`import FileSaver from "file-saver";`

![Screenshot 2022-12-11 at 18 59 51](https://user-images.githubusercontent.com/47661144/206920433-068f7a49-5f0f-4043-a811-45133070390e.png)

Let me know if I can help

**Comment by vinodnimbalkar** [comment]
Yes, please let me know, how can I reproduce this bug (steps to reproduce this bug). so I'll try to fix it.
