### ISSUE TITLE
Unable to open 'pdf.js'

### ISSUE THREAD

**Issue by markfirmware** [vinodnimbalkar/svelte-pdf#6]
<script>
      import PdfViewer from "svelte-pdf";
    </script>

    <PdfViewer url='https://infocenter.nordicsemi.com/pdf/nRF51_RM_v3.0.1.pdf'></PdfViewer>

**Comment by vinodnimbalkar** [comment]
there is another problem with url because **https url** "https://nearlaw.com/PDF/SC/2000/2000-ALL-SCR-1.pdf" and few other https url has tested, its working fine.
https://codesandbox.io/s/svelte-pdf-govhm?file=/App.svelte

**Comment by markfirmware** [comment]
I discovered that it is blank for a period of seconds then

    Unable to open 'pdf.js': File not found (file:///sandbox/node_modules/pdfjs-dist/build/pdf.js).

**Comment by markfirmware** [comment]
@vinodnimbalkar 

Your sandbox

https://codesandbox.io/s/svelte-pdf-govhm?file=/App.svelte

now fails consistently. It takes about thirty seconds to get:

![Screenshot from 2020-10-19 20-24-15](https://user-images.githubusercontent.com/22677068/96525529-b7896400-126a-11eb-8ccf-2f49eaa4d0bf.png)

**Comment by markfirmware** [comment]
Closed pending resolution of https://github.com/vinodnimbalkar/svelte-pdf/issues/8
