### ISSUE TITLE
The arrow on the counter-clockwise button is backwards

### ISSUE THREAD

**Issue by markfirmware** [vinodnimbalkar/svelte-pdf#7]

**Comment by vinodnimbalkar** [comment]
:bug: Arrow corrected on counter-clockwise button :  6d6f0ab18098e5c52f62ef8f810d33220b56625b

**Comment by markfirmware** [comment]
Not yet fixed in readme demo:

Source code of demo page is included in example directory.

https://svelte-pdf.netlify.com

**Comment by vinodnimbalkar** [comment]
Thanks for remind to fix demo, Now it fixed 
check out https://svelte-pdf.netlify.app/

**Comment by markfirmware** [comment]
You are welcome, and thanks.
