### ISSUE TITLE
<PdfViewer> was created without expected prop 'url'

### ISSUE THREAD

**Issue by bluepuma77** [vinodnimbalkar/svelte-pdf#81]
This seems strange, as I should be able to simply use 
```
<PdfViewer data={atob(base64)} />
```
The [readme](https://github.com/vinodnimbalkar/svelte-pdf?tab=readme-ov-file#props) also states that `url` is a required prop.

**Comment by vinodnimbalkar** [comment]
Fix by PR https://github.com/vinodnimbalkar/svelte-pdf/pull/93
