### ISSUE TITLE
The demo site is not found

### ISSUE THREAD

**Issue by Em-ilien** [vinodnimbalkar/svelte-pdf#89]
https://svelte-pdf.netlify.com/

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by vinodnimbalkar** [comment]
Fix by PR https://github.com/vinodnimbalkar/svelte-pdf/pull/94
